### ISSUE TITLE
Navbar scroll

### ISSUE THREAD

**Issue by locmai0808** [creativetimofficial/ct-paper-dashboard-pro-react#1]
![image](https://user-images.githubusercontent.com/18728001/48921662-2333de00-ee56-11e8-8473-d18ace37d54b.png)
The scrolling bar on the navbar looks not as good as the light version. 
![image](https://user-images.githubusercontent.com/18728001/48921689-668e4c80-ee56-11e8-94b8-636fe40b403a.png)

What could be done to fix this? Thank you in advance!

**Comment by locmai0808** [comment]
![image](https://user-images.githubusercontent.com/18728001/48922557-5bd6b600-ee5c-11e8-94c8-00a14b68d9c0.png)

This is the comparision between Paper Dashboard Pro React vs Paper Dashboard Pro HTML. 
The scroll bar on the react version isn't looking good.

**Comment by einazare** [comment]
Hello, there @locmai0808 ,

Thank you for your interest in working with our products.
Why haven't you used our ISSUES_TEMPLATE?

To solve this issue:

- Delete the code inside `src/assets/scss/paper-dashboard/plugins/_plugin-perfect-scrollbar.scss`
- Copy the CSS code from here https://raw.githubusercontent.com/utatti/perfect-scrollbar/master/css/perfect-scrollbar.css
- Paste it inside `src/assets/scss/paper-dashboard/plugins/_plugin-perfect-scrollbar.scss`
- After line 34 inside `src/assets/scss/paper-dashboard/plugins/_plugin-perfect-scrollbar.scss` (`right 0;`) add `left: auto!important;`

Hope this information was of help.

Please, next time use the ISSUES_TEMPLATE provided by us, in a few weeks/days we want to add an automatization for our issues, if you do not use the ISSUES_TEAMPLATE, your issue will be closed automatically and we won't get any notifications. Hope you can understand our situation.

Best,
Manu

**Comment by locmai0808** [comment]
My apologies for not following your templates. And that fixed it! Thank you very much!!!!
