### ISSUE TITLE
[Bug] Cannot run "production" build

### ISSUE THREAD

**Issue by apperside** [creativetimofficial/ct-paper-dashboard-pro-react#12]
### Version
1.2.0
### Reproduction link
Just downloaded and executed the steps in "Steps to reproduce"
### Operating System
Mac os
### Device
macbook pro
### Browser & Version
firefox & chrome
### Steps to reproduce
Hello,
I just downloaded the bundle, ran npm run build and then npm run start and everithing is ok.
Then I run npm run build, the build succeds and then when I run serve -s build I get a blank page with strange errors in the browsers:

This is chrome https://pasteboard.co/JFa01g3.png
This is firefox https://pasteboard.co/JFa0qnl.png

I am using npm 6.14.6 and node 10.22.0, and I didn't edit a single line of code
### What is expected?
The app runs
### What is actually happening?
Blank page with errors in the console

---

**Comment by einazare** [comment]
Hello there, @apperside ,

Thank you for your interest in working with our products.
Please go inside `package.json` file, and delete the homepage prop.
We'll add this in our live docs on our next update of the product, so please leave the issue open.

Best,
Manu

**Comment by apperside** [comment]
It worked,
thank you!
