### ISSUE TITLE
[Bug] Sass Error: expected selector.

### ISSUE THREAD

**Issue by hxgong** [creativetimofficial/ct-paper-dashboard-pro-react#13]
### Version
1.2.0
### Reproduction link
http://localhost
### Operating System
windows
### Device
windows
### Browser & Version
chrome
### Steps to reproduce
(./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./src/main/webapp/app/app.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected selector.
  ╷
7 │ .table not(.btn-group) .btn + .btn,
  │           ^
  ╵
  src\main\webapp\content\scss\paper-dashboard\react\custom\_buttons.scss 7:11   @import
  src\main\webapp\content\scss\paper-dashboard\react\react-differences.scss 4:9  @import
  src\main\webapp\content\scss\paper-dashboard.scss 99:9                         @import

### What is expected?
scss files can be compiled
### What is actually happening?
compile error

---

**Comment by einazare** [comment]
Hello there, @hxgong ,

Thank you for your interest in working with our products.
Please go inside `src/assets/scss/paper-dashboard/react/custom/_buttons.scss` and replace:
```
.table not(.btn-group) .btn + .btn,
```
With
```
.table :not(.btn-group) .btn + .btn,
```

Also, please leave the issue open.

Best,
Manu
