### ISSUE TITLE
[Feature Request] Show logo in expanded Sidebar on className="logo-normal"

### ISSUE THREAD

**Issue by JustinHaut** [creativetimofficial/ct-paper-dashboard-pro-react#19]
### What is your enhancement?
Hello,

Do you have any advice on keeping the company logo on the sidebar when sidebar is expanded? So it looks the same as "logo-mini" class?

Thank you,
Justin

**Comment by sajadevo** [comment]
**Hi @JustinHaut**

Thanks for using our product, on the scss files share for this class name: `a.logo-mini` and change the opacity to 1.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
