### ISSUE TITLE
[Bug] Sidebar icons disappear when hovering on white sidebar theme

### ISSUE THREAD

**Issue by enkeledi** [creativetimofficial/ct-paper-dashboard-pro-react#22]
### Version
1.3.0
### Reproduction link
https://user-images.githubusercontent.com/1541780/167233170-433803ef-48f1-448f-8319-e2ea40b78530.png
### Operating System
macOS Monterey (12.3.1)
### Device
iMac
### Browser & Version
Safari Version 15.4 (17613.1.17.1.13)
### Steps to reproduce
When I select white sidebar color from the fixed widget, and then hover over the sidebar selections, the icons disappear randomly. The issue happens on the web demo as well.
### What is expected?
Icons should not disappear.
### What is actually happening?
Icons disappearing randomly, one or two at a time.

---

**Comment by enkeledi** [comment]
Only happens on Safari. Chrome seems to work fine.

**Comment by sajadevo** [comment]
**Hi @enkeledi**

Thanks for reporting this issue we'll fix it for future updates.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
