### ISSUE TITLE
[Bug] Calendar events issue

### ISSUE THREAD

**Issue by daniel18acevedo** [creativetimofficial/ct-paper-dashboard-pro-react#24]
### Version
13
### Reproduction link
https://codepen.io/
### Operating System
Windows
### Device
Chrome
### Browser & Version
Chrome
### Steps to reproduce
Go to calender component

Select several hours to create an event

Set the title of the event

### What is expected?
The event end time should rich the end time set
### What is actually happening?
The event is very short, the end hour doesn't rich to the end hour set

---

**Comment by sajadevo** [comment]
**Hi @daniel18acevedo**

For more details related to the calendar please take a look to its official documentation.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
