### ISSUE TITLE
[Bug] Not able to run the install command

### ISSUE THREAD

**Issue by dbrazeauPositron** [creativetimofficial/ct-paper-dashboard-pro-react#27]
### Version
1.3.1
### Reproduction link
localhost:3000
### Operating System
Windows
### Device
PC
### Browser & Version
Chrome 110.0.5481.104
### Steps to reproduce
Unzip the zip file from you website
Open the folder with the most recent version of visual studio code
Open a terminal
Run the command "npm install"
### What is expected?
Get a full installation of the project
### What is actually happening?
Getting this error : 
While resolving: paper-dashboard-pro-react@1.3.1
Found: react@18.2.0
node_modules/react
  react@"18.2.0" from the root project

Could not resolve dependency:
peer react@"17.x.x" from react-bootstrap-wizard@0.0.9
node_modules/react-bootstrap-wizard
  react-bootstrap-wizard@"0.0.9" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

---

**Comment by sajadevo** [comment]
Hey there,

This issue is fixed on v1.3.2.

Regards,
Sajad
