### ISSUE TITLE
Deploy to Heroku fails to load

### ISSUE THREAD

**Issue by sorenzi** [creativetimofficial/ct-paper-dashboard-pro-react#3]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Deploying to heroku using the steps you provided should work

# Current Behavior
Once the app is deploy on heroku it fails to load 

# Failure Information (for bugs)

Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://testapporen.herokuapp.com/creativetimofficial/paper-dashboard-pro-react/static/css/1.9eb5c574.chunk.css".
testapporen.herokuapp.com/:1 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://testapporen.herokuapp.com/creativetimofficial/paper-dashboard-pro-react/static/css/main.8b67cc70.chunk.css".
1.fb7078ce.chunk.js:1 Uncaught SyntaxError: Unexpected token <
main.e9c135eb.chunk.js:1 Uncaught SyntaxError: Unexpected token <

![test](https://user-images.githubusercontent.com/133311/50427598-442a8d00-0861-11e9-89a0-50fa96426168.png)

## Steps to Reproduce

Just follow the steps to deploy on heroku from your guide

https://demos.creative-tim.com/now-ui-dashboard-pro-react/?_ga=2.121407617.806140826.1545693448-240328354.1543013399#/documentation/tutorial

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
iMac
* Operating System:
Mojave 10.14.2 Beta
* Browser and Version:
Chrome Version 71.0.3578.98

Please include any relevant log snippets or files here.

**Comment by PrimeItWorks** [comment]
hello dude! I have the same problem deploying to Azure Web App. 
How do you solved this?

**Comment by sorenzi** [comment]
I didnt, I just uploaded the build folder to s3 and hosted it as a static website
you need to run npm react-scripts build and deploy the build folder to your azure webapp

**Comment by einazare** [comment]
Hello guys,

Sorry for this late response, I've just realized that I didn't add any response.
To solve the issues you just need to delete the homepage prop from the package.json file.

Best,
Manu
