### ISSUE TITLE
Entire page of space after the Footer which scrolls up and out of view

### ISSUE THREAD

**Issue by twospace-rob** [creativetimofficial/ct-paper-dashboard-pro-react#5]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Yes ] I am running the latest version
- [ Yes ] I checked the documentation and found no answer
- [ Yes ] I checked to make sure that this issue has not already been filed
- [ Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

When scrolling and reach the footer, the scrolling stops when the footer is on the bottom of the page.

# Current Behavior

What is the current behavior?

Page keeps scrolling. Seems to be an entire page worth of scrolling added after the footer. Until everything is out of view. The ps__rail-y div seems to add it

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. On any page, scroll down and you'll keep scrolling

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows 10
* Browser and Version: Google Chrome - Version 73.0.3683.86 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.

![image](https://user-images.githubusercontent.com/35083338/54975650-e2a6c580-4feb-11e9-97a2-99e7d1321ff4.png)

**Comment by einazare** [comment]
Hello there, @twospace-rob ,

Thank you for your interest in working with our product.
This issue has been solved here: #1 .
Please refer to that issue, and if your issue persists, come back here.

Best,
Manu

**Comment by twospace-rob** [comment]
Thankyou @EINazare that fixed the issue.

I'm not sure if you're aware that the issue still exists in your demo site too and the Paper Dashboard PRO React bundle, so others may experience the same issue too.

**Comment by einazare** [comment]
Hello again @twospace-rob ,

Yes, we are aware, but to solve this we would have to make an update to the entire product, not only on our live demo. And this requires some time, which at the moment we do not have.
When we'll have some spare time we'll make the proper updates and changes.

Best,
Manu
