### ISSUE TITLE
Modal headers & footer layout issues

### ISSUE THREAD

**Issue by tylerdavis** [creativetimofficial/ct-paper-dashboard-pro-react#6]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

Hey there.  I just purchased a business license for this theme and have run into a small issue I was hoping you might be able to address.  If I have left anything important out, please let me know and I will update this issue accordingly.

Thank you very much

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Modal headers: The default bootstrap modal layout should render the documented styles correctly, honoring the vertical alignment in the examples.    

Modal footers: The right padding on the modal footers needs to be adjusted.

# Current Behavior

I use the data-confirm-modal gem for rails confirmations, which renders the default modal.  Additionally I have several modals that I built prior to beginning to implement your theme that are built to the bootstrap 4 spec.  The header content does not align correctly.  The close button ends up below the header title in all cases.

<img width="540" alt="Screenshot 2019-06-09 09 25 07" src="https://user-images.githubusercontent.com/490887/59161628-185f3480-8a9a-11e9-967c-cdc63b8eaf5a.png">

I see that certain examples in your documentation also behave like this.

<img width="1043" alt="Screenshot 2019-06-09 09 28 59" src="https://user-images.githubusercontent.com/490887/59161632-1eedac00-8a9a-11e9-9c6e-363fc10f44ae.png">

# Failure Information (for bugs)

Using the documented modal layouts will produce this bug.

## Steps to Reproduce

See your documentation on modals for steps to reproduce.

## Context

My application is built on ruby on rails.  Additionally, the frontend is a mix of vanilla rails / bootstrap / erb and reactstrap.

* Device: Macbook Pro
* Operating System: MacOs
* Browser and Version: Safari / Chrome / Firefox

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there, @tylerdavis ,

Thank you for your interest in working with our products.
You can go ahead and add the following css:
```
.modal-header {
    display: flex !important;
}
```

Best,
Manu
