### ISSUE TITLE
[Bug] Layout Admin - All pages in layout admin goes out of container

### ISSUE THREAD

**Issue by GSolari79** [creativetimofficial/ct-paper-dashboard-pro-react#9]
### Version
1.0.0
### Reproduction link
ask me about it through personal message
### Operating System
Windows
### Device
Chrome
### Browser & Version
80.0.3987.116 (Official Build) (64-bit)
### Steps to reproduce
Login and navigate to any page from a Windows 10 machine.
### What is expected?
Content to be placed inside admin layout container and not overlapping.
### What is actually happening?
The content are placed outside of main container of layout admin scrolling down way below the content.

---
### Solution
I don't have a solution
### Additional comments
 The issue occurs only in windows machines. In Ubuntu with latest chrome and Mozila functions as expected.

**Comment by einazare** [comment]
Hello there, @GSolari79 ,

Thank you for your interest in working with our products and for following our rules of opening a Github issue.
Does this solve your issue: https://github.com/creativetimofficial/ct-paper-dashboard-pro-react/issues/1

Best,
Manu

**Comment by GSolari79** [comment]
Thanks for the fast reply.

I did the changes proposed and it did not fix the way the scrollbar looks. My issues is different though and it occurs only when tested using windows 10.

Have a look at the screenshots:


![print screen3](https://user-images.githubusercontent.com/23034288/75157746-6ba70f00-571d-11ea-8268-bbb1e7d9f0c7.png)
![print screen2](https://user-images.githubusercontent.com/23034288/75157752-706bc300-571d-11ea-95fc-0a1f933901b8.png)
![print screen](https://user-images.githubusercontent.com/23034288/75157759-72ce1d00-571d-11ea-97ba-59b132a3a850.png)

**Comment by GSolari79** [comment]
In Ubuntu the content is placed inside the container (light grey background):

![correct](https://user-images.githubusercontent.com/23034288/75158322-8a59d580-571e-11ea-8949-6cf16abc642c.png)

**Comment by einazare** [comment]
Hello again, @GSolari79 ,

Please go inside `src/layouts/Admin.jsx` and delete the following bits of code:
```
  componentDidMount() {
    if (navigator.platform.indexOf("Win") > -1) {
      document.documentElement.className += " perfect-scrollbar-on";
      document.documentElement.classList.remove("perfect-scrollbar-off");
      ps = new PerfectScrollbar(this.refs.mainPanel);
    }
  }
  componentWillUnmount() {
    if (navigator.platform.indexOf("Win") > -1) {
      ps.destroy();
      document.documentElement.className += " perfect-scrollbar-off";
      document.documentElement.classList.remove("perfect-scrollbar-on");
    }
  }
```
That will solve your issue.

Best,
Manu

**Comment by GSolari79** [comment]
Thanks a lot Manu for the immediate support. It resolved the issue!

Best regards,
George
